# Generated by Django 5.1 on 2024-08-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='backdrop_path',
            new_name='backdrop_path_original',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster_path',
            new_name='backdrop_path_w500',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path_w500',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
