# Generated by Django 5.1 on 2024-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_backdrop_path_movie_backdrop_path_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('poster_path_w500', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_path_original', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path_w500', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path_original', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_url', models.URLField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
